# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://nouveal.visualstudio.com/DefaultCollection/iOS/_git/NouvealPodsRepo'


target 'CountryPickerTextField-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountryPickerTextField-Example
  pod 'CountryPickerTextfield', :path => '~/Work/CountryPickerTextfield'
  pod 'SwiftyGestureRecognizer'

end
